Adds support for the new react-native condition
wevm/isows pull request #9
Opened 2024-03-12 23:36 UTC by iketw

Adds support for the updated `react-native` community condition:

https://metrobundler.dev/docs/package-exports/#replacing-browser-and-react-native-fields

Tested by adding this new condition to the package from a newly created react-native app.

2024-03-12 23:37 UTC, iketw commented
@jxom please, let me know if you want a sample app. I didn't provide one since the change is quite simple. Thanks

2024-03-14 19:02 UTC, tmm requested changes
Please add a changeset with `bun changeset`

2024-03-14 19:02 UTC, tmm commented on src/package.json
> +			"react-native": "./_esm/native.js"
default should be the last condition

```suggestion
			"react-native": "./_esm/native.js",
			"default": "./_cjs/index.js"
```

2024-03-14 19:06 UTC, iketw commented
@tmm thanks for reviewing. Accepted the change and added the changeset

2024-03-14 20:16 UTC, merged